# Generated by Django 4.1.7 on 2023-04-17 13:33

import commerce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_productimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=commerce.models.CloudinaryField(max_length=255),
        ),
    ]
