# Generated by Django 4.1.7 on 2023-04-24 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_customerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product image'),
        ),
    ]
