# Generated by Django 4.1.7 on 2023-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
