# Generated by Django 4.1.7 on 2023-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herosection_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroSection',
            new_name='HeroContent',
        ),
    ]
