# Generated by Django 4.1.7 on 2023-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_herosection_herocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontent',
            name='hero_paragraph',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
