# Generated by Django 4.1.7 on 2023-04-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_herocontent_hero_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_primary_text', models.CharField(max_length=200)),
                ('hero_secondary_text', models.CharField(max_length=200)),
                ('hero_paragraph', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('whatsapp', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('facebook', models.CharField(max_length=20)),
                ('short_about_us', models.CharField(max_length=200)),
                ('long_about_us', models.TextField()),
            ],
        ),
    ]
