# Generated by Django 4.1.7 on 2023-04-24 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_sitecontent_buniess_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='BusinessInfo',
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='buniess_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='buniess image'),
        ),
    ]
